# mongodb://root:root@localhost:27017
version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootsy
      MONGO_INITDB_ROOT_PASSWORD: rootsy
    ports:
    - 27017:27017
    volumes:
    - /Dockercompose:/data/db